# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Yahya Baassou
title: Backend Software Engineer
email: yahyabaassou@gmail.com
website: https://yabaa.github.io/resume/

# Social links
github_username:  yabaa
flickr_username: yahyabaassou
instagram_username: yahya.baa
linkedin_username: yahya-baassou-9a3ba0b6
# twitter_username: facespics
# dribbble_username: jekyll
# facebook_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, constantly looking for new projects and new technologies, I devote a real passion for software development. I have 8 years of experience as Java developer working for different sectors, like radiocommunication, insurance or finance.

  The technical stack that I have the most experience working with is:
    <mark>Java</mark>,
    <mark>Spring Boot</mark>,
    <mark>PostgreSQL</mark>,
    <mark>Git</mark>,
    <mark>Gradle</mark>,
    <mark>Maven</mark>,
    <mark>AWS</mark>

  I am currently based in Singapore but looking to relocate back to France. I am looking for a <mark>full remote</mark> job as Java/Spring developper.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm not programming
more_content: | # this will include new lines to allow paragraphs
  I really love traveling around the world. I have been travelling to many countries, mainly in Europe and Asia. Check my [Flickr](https://www.flickr.com/photos/yahyabaassou/) account to have a look on some pictures.

  I also do a lot of sports such as soccer, tennis, badminton, running, ...

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
